openapi: "3.0.3"

info:
  version: 1.0.0
  title: SA Liabilities Payment Details API

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production

components:
  headers:
    correlationId:
      description: Unique Transaction Reference
      schema:
        type: string
        format: uuid

  parameters:
    nino:
      name: NINO
      in: path
      description: National Insurance Number
      schema:
        type: string
        pattern: '^[A-Z]{2}[0-9]{6}[A-Z]$'
      required: true

  schemas:
    BalanceDetail:
      type: object
      properties:
        payableAmount:
          type: number
          format: double
          description: The sum of any non-zero charges whose payment due date is within 30 days.
          minimum: -99999999999.99
          maximum: 99999999999.99
        payableDueDate:
          type: string
          format: date
          description: |
              Next payment date for charges due.
              Format: YYYY-MM-DD.
        pendingDueAmount:
          type: number
          format: double
          description: The sum of any charges whose payment is pending (i.e., due on a date later than 30 days).
          minimum: -99999999999.99
          maximum: 99999999999.99
        pendingDueDate:
          type: string
          format: date
          description: |
              The date by when the next pending charge must be paid.
              Format: YYYY-MM-DD.
        overdueAmount:
          type: number
          format: double
          description: The total amount associated with charges whose due date is in the past.
          minimum: -99999999999.99
          maximum: 99999999999.99
        totalBalance:
          type: number
          format: double
          description: Total balance should be equal to the sum of the balance due within 30 days, balance not due in 30 days, and overdue amount.
          minimum: -99999999999.99
          maximum: 99999999999.99
      required:
        - payableAmount
        - pendingDueAmount
        - overdueAmount
        - totalBalance

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          enum:
            - "1002"
            - "1113"
        errorDescription:
          type: string
          enum:
            - "NINO not found"
            - "Invalid path parameters"
      required:
        - errorCode
        - errorDescription

paths:
  /payments/self-assessment/liabilities/nino/{NINO}:
    get:
      summary: Get SA liabilities payment details
      parameters:
        - $ref: '#/components/parameters/nino'
      responses:
        '200':
          description: SA Liabilities payment details
          content:
            application/json:
              schema:
                type: object
                properties:
                  balanceDetails:
                    type: array
                    items:
                      $ref: '#/components/schemas/BalanceDetail'
        '400':
          description: Invalid request parameters or NINO not found
          headers:
            CorrelationId:
              $ref: '#/components/headers/correlationId'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - {}